language: python

python:

- 3.6

before_install:

- python --version

- pip install -U pip

- pip install -U pytest

- pip install -U pytest-cov

- pip install -r requirements.txt

script:

- pytest --cov=com.faculdadeimpacta.calculadora com/faculdadeimpacta/calculadora/test/